name: px4_vxworks
on_project_start: pwd
windows:
  - editor:
      layout: main-vertical
      panes:
        - vim platforms/vxworks/src/px4/common/main.cpp
  - shell:
      layout: main-vertical
      panes:
        - Tools/vxworks/build_px4_using_docker.sh
  - running:
      layout: main-vertical
      panes:
        - Tools/vxworks/ftpd.sh
        - Tools/vxworks/run_px4.sh
  - docker:
      layout: main-vertical
      panes:
        - lazydocker
  - telnet:
      layout: main-vertical
      panes:
        - telnet 192.168.5.61
  - simulator:
      layout: main-vertical
      panes:
        - mavproxy.py --master=udpout:192.168.5.61:14560 --out=udp:0.0.0.0:14550 --out=udp:0.0.0.0:14560
        - HEADLESS=1 ./Tools/simulation/jmavsim/jmavsim_run.sh -q -s -u -p 14560 -r 250